version: '3.9'

volumes:
  db_data:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer
      - MSSQL_DBNAME=cardbid
    ports:
      - 1436:1433
    volumes:
      - db_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123 -Q 'SELECT 1' || exit 1"]
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 2s

  db.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./dataMigration:/docker-entrypoint-initdb.d
    depends_on:
      db:
        condition: service_healthy
    command: "/bin/bash -c '/opt/mssql-tools/bin/sqlcmd -S db -U sa -P Password123 -d master -i docker-entrypoint-initdb.d/init.sql && echo \"Configuration done!\"'"